desktop_min_zoom = 0.42
desktop_max_zoom = 2.6
desktop_default_zoom = 1.0
desktop_node_scale = 1.0

mobile_min_zoom = 0.60
mobile_max_zoom = 7.0
mobile_default_zoom = 1.0
mobile_node_scale = 0.65
mobile_label_min_zoom = 2.2
