alter table agent_tasks add column if not exists operator_handoff jsonb;
alter table agent_tasks add constraint agent_tasks_operator_handoff_object check (operator_handoff is null or jsonb_typeof(operator_handoff) = 'object');

create or replace function daemon_update_agent_task(p_user_id uuid,p_task_id uuid,p_expected_status text,p_updates jsonb)
returns boolean language plpgsql security definer set search_path=public as $$
begin
 update agent_tasks set status=coalesce(p_updates->>'status',status),message=coalesce(p_updates->>'message',case when p_updates->>'status'in('completed','failed','blocked','cancelled')then'client_review'else message end),base_commit=coalesce(p_updates->>'base_commit',base_commit),completed_commit=coalesce(p_updates->>'completed_commit',completed_commit),branch_name=coalesce(p_updates->>'branch_name',branch_name),worktree_path=coalesce(p_updates->>'worktree_path',worktree_path),result=coalesce(p_updates->>'result',result),error=coalesce(p_updates->>'error',error),operator_handoff=case when p_updates?'operator_handoff' then nullif(p_updates->'operator_handoff','null'::jsonb) else operator_handoff end,verification_attempts=coalesce((p_updates->>'verification_attempts')::integer,verification_attempts),resolver_attempts=coalesce((p_updates->>'resolver_attempts')::integer,resolver_attempts),cancel_requested=coalesce((p_updates->>'cancel_requested')::boolean,cancel_requested),started_at=case when p_updates?'started_at'then(p_updates->>'started_at')::timestamptz else started_at end,completed_at=case when p_updates?'completed_at'then(p_updates->>'completed_at')::timestamptz else completed_at end,updated_at=now()
 where id=p_task_id and user_id=p_user_id and status=p_expected_status;return found;
end; $$;

create or replace function request_agent_task_retry(p_task_id uuid,p_expected_updated_at timestamptz)
returns boolean language plpgsql security definer set search_path=public as $$
begin
 update agent_tasks set status=case status when'failed'then'queued'when'blocked'then case when operator_handoff is null then'ready'else'queued'end end,message='daemon_review',cancel_requested=false,completed_at=null,retry_generation=retry_generation+1,resolver_attempts=case when status='blocked'then 0 else resolver_attempts end,updated_at=now()
 where id=p_task_id and user_id=auth.uid()and updated_at=p_expected_updated_at and status in('failed','blocked')and worktree_path is not null and branch_name is not null;return found;
end; $$;

drop function if exists daemon_upsert_agent_task_turn(uuid,text,text,text,text,text,text,text,text,uuid,text,jsonb,text,text);
create function daemon_upsert_agent_task_turn(p_user_id uuid,p_prompt_id text,p_repository text,p_prompt text,p_output text,p_error text,p_provider text,p_model text,p_reasoning text,p_conversation_id uuid,p_mode text,p_targeted_feature_paths jsonb,p_status text,p_status_detail text default null,p_operator_handoff jsonb default null)
returns void language plpgsql security definer set search_path=public as $$
declare conversation_id_value uuid;begin
 if p_mode not in('planning','ask','bridge','impl_prep') or p_status not in('running','completed','failed','blocked','cancelled')then raise exception 'Unsupported direct task turn';end if;
 if p_operator_handoff is not null and jsonb_typeof(p_operator_handoff) <> 'object' then raise exception 'operator handoff must be an object';end if;
 conversation_id_value:=coalesce(p_conversation_id,gen_random_uuid());insert into agent_conversations(id,user_id,repository,legacy_conversation_id)values(conversation_id_value,p_user_id,p_repository,conversation_id_value::text)on conflict(id)do update set updated_at=now();
 insert into agent_tasks(id,user_id,conversation_id,prompt_id,repository,prompt,provider,model,reasoning,planning_mode,targeted_feature_paths,status,result,error,started_at,completed_at,message,task_type,source,status_detail,operator_handoff) values(gen_random_uuid(),p_user_id,conversation_id_value,p_prompt_id,p_repository,p_prompt,coalesce(p_provider,''),coalesce(p_model,''),coalesce(p_reasoning,''),p_mode='planning',coalesce(p_targeted_feature_paths,'[]'::jsonb),p_status,coalesce(p_output,''),coalesce(p_error,''),now(),case when p_status in('completed','failed','blocked','cancelled')then now()else null end,'client_complete',p_mode,'direct_prompt',coalesce(p_status_detail,''),p_operator_handoff) on conflict(user_id,prompt_id)do update set result=excluded.result,error=excluded.error,status=excluded.status,status_detail=excluded.status_detail,operator_handoff=excluded.operator_handoff,provider=excluded.provider,model=excluded.model,reasoning=excluded.reasoning,completed_at=excluded.completed_at,updated_at=now();
end; $$;

create or replace function get_client_review_inbox() returns jsonb language sql stable security definer set search_path=public as $$
 with owner as(select auth.uid() user_id) select jsonb_build_object('communications',coalesce((select jsonb_agg(to_jsonb(r)order by purpose)from(select purpose,content,updated_at from communications,owner where communications.user_id=owner.user_id and communications.message='client_review'order by purpose limit 10)r),'[]'),'daemonPayloads',coalesce((select jsonb_agg(to_jsonb(r)order by kind)from(select kind,payload,updated_at from daemon_payloads,owner where daemon_payloads.user_id=owner.user_id and daemon_payloads.message='client_review'order by kind limit 3)r),'[]'),'agentTasks',coalesce((select jsonb_agg(to_jsonb(r)order by updated_at,id)from(select id,repository,prompt,provider,model,reasoning,planning_mode,targeted_feature_paths,status,queue_sequence,created_at,started_at,completed_at,error,status_detail,operator_handoff,verification_attempts,resolver_attempts,cancel_requested,retry_generation,updated_at from agent_tasks,owner where agent_tasks.user_id=owner.user_id and agent_tasks.message='client_review'order by updated_at,id limit 50)r),'[]'));
$$;

drop function if exists get_agent_conversation_page(timestamptz,uuid,integer);
create function get_agent_conversation_page(p_cursor_completed_at timestamptz default null,p_cursor_id uuid default null,p_limit integer default 31)
returns table(id uuid,prompt_id text,task_id uuid,conversation_id uuid,repository text,prompt text,provider text,model text,reasoning text,mode text,source text,targeted_feature_paths jsonb,status text,status_detail text,operator_handoff jsonb,created_at timestamptz,started_at timestamptz,completed_at timestamptz,updated_at timestamptz) language sql stable security definer set search_path=public as $$
 with latest as(select distinct on(conversation_id)* from agent_tasks where user_id=auth.uid() order by conversation_id,coalesce(completed_at,updated_at)desc,id desc) select id,prompt_id,id,conversation_id,repository,left(prompt,240),provider,model,reasoning,case task_type when'planning'then'planning'when'ask'then'ask'when'bridge'then'bridge'when'impl_prep'then'impl_prep'else'standard'end,source,targeted_feature_paths,status,status_detail,operator_handoff,created_at,started_at,completed_at,updated_at from latest where completed_at is not null and(p_cursor_completed_at is null or(completed_at,id)<(p_cursor_completed_at,p_cursor_id))order by completed_at desc,id desc limit least(greatest(p_limit,1),31);
$$;

drop function if exists get_agent_conversation_tasks(uuid);
create function get_agent_conversation_tasks(p_conversation_id uuid)
returns table(id uuid,prompt_id text,task_id uuid,conversation_id uuid,repository text,prompt text,output text,error text,provider text,model text,reasoning text,mode text,source text,targeted_feature_paths jsonb,status text,status_detail text,operator_handoff jsonb,created_at timestamptz,started_at timestamptz,completed_at timestamptz,updated_at timestamptz) language sql stable security definer set search_path=public as $$
 select id,prompt_id,id,conversation_id,repository,prompt,result,error,provider,model,reasoning,case task_type when'planning'then'planning'when'ask'then'ask'when'bridge'then'bridge'when'impl_prep'then'impl_prep'else'standard'end,source,targeted_feature_paths,status,status_detail,operator_handoff,created_at,started_at,completed_at,updated_at from agent_tasks where user_id=auth.uid()and conversation_id=p_conversation_id order by created_at,id;
$$;

drop function if exists search_agent_conversations(text,integer);
create function search_agent_conversations(p_query text,p_limit integer default 50)
returns table(id uuid,prompt_id text,task_id uuid,conversation_id uuid,repository text,prompt text,provider text,model text,reasoning text,mode text,source text,targeted_feature_paths jsonb,status text,status_detail text,operator_handoff jsonb,created_at timestamptz,started_at timestamptz,completed_at timestamptz,updated_at timestamptz) language sql stable security definer set search_path=public as $$
 select distinct on(task.conversation_id)task.id,task.prompt_id,task.id,task.conversation_id,task.repository,left(task.prompt,240),task.provider,task.model,task.reasoning,case task.task_type when'planning'then'planning'when'ask'then'ask'when'bridge'then'bridge'when'impl_prep'then'impl_prep'else'standard'end,task.source,task.targeted_feature_paths,task.status,task.status_detail,task.operator_handoff,task.created_at,task.started_at,task.completed_at,task.updated_at from agent_tasks task where task.user_id=auth.uid()and(nullif(trim(p_query),'')is null or concat_ws(' ',task.prompt,task.result,task.repository,task.targeted_feature_paths::text,task.provider,task.model,task.task_type,task.status)ilike '%'||trim(p_query)||'%')order by task.conversation_id,coalesce(task.completed_at,task.updated_at)desc,task.id desc limit least(greatest(p_limit,1),200);
$$;

-- Preserve the complete inbox contract while adding the handoff payload to task rows.
create or replace function get_client_review_inbox() returns jsonb language sql stable security definer set search_path=public as $$
 with owner as(select auth.uid() user_id) select jsonb_build_object(
 'communications',coalesce((select jsonb_agg(to_jsonb(r)order by purpose)from(select purpose,content,updated_at from communications,owner where communications.user_id=owner.user_id and communications.message='client_review'order by purpose limit 10)r),'[]'),
 'daemonPayloads',coalesce((select jsonb_agg(to_jsonb(r)order by kind)from(select kind,payload,updated_at from daemon_payloads,owner where daemon_payloads.user_id=owner.user_id and daemon_payloads.message='client_review'order by kind limit 4)r),'[]'),
 'agentTasks',coalesce((select jsonb_agg(to_jsonb(r)order by updated_at,id)from(select id,repository,prompt,provider,model,reasoning,planning_mode,targeted_feature_paths,status,queue_sequence,created_at,started_at,completed_at,error,status_detail,operator_handoff,verification_attempts,resolver_attempts,cancel_requested,retry_generation,updated_at from agent_tasks,owner where agent_tasks.user_id=owner.user_id and agent_tasks.message='client_review'order by updated_at,id limit 50)r),'[]'),
 'taskDeletionRequests',coalesce((select jsonb_agg(to_jsonb(r)order by updated_at,id)from(select id,task_id,prompt_id,status,error,updated_at from agent_task_deletion_requests,owner where agent_task_deletion_requests.user_id=owner.user_id and agent_task_deletion_requests.message='client_review'order by updated_at,id limit 50)r),'[]'),
 'architectureViews',coalesce((select jsonb_agg(to_jsonb(r)order by updated_at,id)from(select id,prompt_id,repository,base_commit,final_commit,targeted_feature_paths,generation,status,changed_files,architecture_document,error,failure_details,provider,model,reasoning,requested_at,started_at,completed_at,created_at,updated_at from architecture_views,owner where architecture_views.user_id=owner.user_id and architecture_views.message='client_review'order by updated_at,id limit 20)r),'[]'),
 'architectureProgressEvents',coalesce((select jsonb_agg(to_jsonb(r)order by created_at,id)from(select id,architecture_view_id,generation,stage,stage_order,attempt,total_attempts,detail,created_at,updated_at from architecture_view_progress_events,owner where architecture_view_progress_events.user_id=owner.user_id and architecture_view_progress_events.message='client_review'order by created_at,id limit 50)r),'[]'),
 'featureExecutionRuns',coalesce((select jsonb_agg(to_jsonb(r)order by updated_at,id)from(select id,project_directory,feature_file_path,status,cancel_requested,command,parameter_file_path,entry_point_path,started_at,completed_at,exit_code,stdout_tail,stderr_tail,error,updated_at from feature_execution_runs,owner where feature_execution_runs.user_id=owner.user_id and feature_execution_runs.message='client_review'order by updated_at,id limit 50)r),'[]'),
 'daemonEvents',coalesce((select jsonb_agg(to_jsonb(r)order by created_at,id)from(select id,event_type,task_id,severity,content,created_at,updated_at from daemon_events,owner where daemon_events.user_id=owner.user_id and daemon_events.message='client_review'order by created_at,id limit 50)r),'[]')
 );
$$;
